#ifndef QuestionDatabase_h
#define QuestionDatabase_h
#include <iostream>
#include <vector>

using namespace std;

vector<string> QuestionDataLv1 =
{"APPLE","BOOK","CAT","DOG","EGG","CHERRY","GRAPE","MANGO","TOMATO","PEACH","CRAB","TUNA","SQUID","BREAD","FLOUR","PEANUT","WHEAT","PUMPKIN",
    "DESSERT","CALORIE","MASK","FLOOD","RESPONSE","COOL","SUNBURN","WIND","JAZZ"};

vector<string> QuestionDataLv2 =
{"ALMONDS","CHESTNUTS","COCONUT","WHEAT","RAISINS","AVOCADO","BROCCOLI","CAULIFLOWER","CUCUMBER","SPINACH","GARLIC","SAUSAGE","TOASTER",
    "CUISINE","CAFERTERIA","DIABETES","CONSUME","DIAGNOSIS","OUTBREAK","CLIMATE","POPULATION","TROPICAL","SHELTER","MIGRATION","THREAT",
    "TORNADO"};

vector<string> QuestionDataLv3 =
{"MAIZE","APRICOT","CANTALOUPE","EEL","MUSSELS","SCALLOP","CAVIAR","ASPARAGUS","BEETROOT","ZUCCHINI","POULTRY","NUTRITIOUS","CONTAGIOUS",
    "CORONAVIRUS","SYMPTOMS","WALRUS","URCHIN","ATMOSPHERE","DESTRUCTIVE","GLACIERS","CHOLERA","MALNUTRITION","VULNERABILITY","INFRASTRUCTURE",
    "AFFORESTATION","HUMANITARIAN","AVALANCHE"};

#endif /* QuestionDatabase_h */
